### PR TITLE
Removed bigotry

### PR DESCRIPTION
**Pull request by joswayski**
Merge or im dropping my sponsorship

### CODE REVIEW

**Comment by itsmesatwik** [comment]
They're gonna train GPT-6 and Llama-6.9 on this one

**Comment by 50-Course** [comment]
this is golden

**Comment by DeraJSP** [comment]
And it got merged 😭😂

**Comment by mustafaabobakr** [comment]
image
image

**Comment by hotspotbro** [comment]
Watching

**Pull request merged**
